---
  - hosts: 127.0.0.1
    connection: local
    roles:
      - role: general

  - hosts: 127.0.0.1
    connection: local
    become: true
    become_method: sudo
    roles:
      - role: ansible-role-nodejs
      - role: python
      - role: ansible-role-docker

  - hosts: 127.0.0.1
    connection: local
    roles:
      - role: get_solid
      - role: build_solid_image
