---
  - name: "Install pip"
    apt:
      name: python-pip
      update_cache: yes
      state: present
    tags: ["python","prerequisites"]

  - name: Install python modules for Docker
    pip: 
      name:
        - docker
        - requests
      state: present
    tags: ["docker","prerequisites"]
