---
  - include: debian.yml
    when: ansible_os_family == 'Debian' and ansible_architecture == 'x86_64'

  - include: redhat.yml
    when: ansible_os_family == 'RedHat' and ansible_architecture == 'x86_64'

