---
  - name: "Check if Solid folder exists"
    stat:
      path: /home/georgemanakanatas/Solid/SolidAnsible/test
    register: solid_server_code
    tags: ["solid","get_solid"]
  
  - name: "Create Solid folder"
    file:
      path: "{{ solid_folder_path_debian }}"
      state: directory
      mode: 0775
      recurse: yes
    when: solid_server_code.stat.exists == False
    become: true
    become_method: sudo
    tags: ["solid","get_solid"]

  - name: "Pull solid from git"
    git:
      repo: "{{ solid_server_url }}"
      dest: "{{ solid_folder_path_debian }}"
    when: solid_server_code.stat.exists == False
    become: true
    become_method: sudo
    tags: ["solid","get_solid"]
    
  - name: "Replace config.json-default file"
    copy:
      src: config.json-default
      dest: "{{ solid_folder_path_debian }}"
      owner: root
      group: root
    become: true
    become_method: sudo
    tags: ["solid","get_solid"]
 
  - name: "replace Dockerfile"
    copy:
      src: Dockerfile
      dest: "{{ solid_folder_path_debian }}"
      owner: root
      group: root
    become: true
    become_method: sudo
    tags: ["solid","get_solid"]
